db.pokemon.insertMany([
  { nome: "Bulbasaur", tipo: "Grama/Veneno", nivel: 5, habilidade: "Crescimento" },
  { nome: "Ivysaur", tipo: "Grama/Veneno", nivel: 16, habilidade: "Folha Navalha" },
  { nome: "Venusaur", tipo: "Grama/Veneno", nivel: 32, habilidade: "Raio Solar" },
  { nome: "Charmander", tipo: "Fogo", nivel: 5, habilidade: "Chama" },
  { nome: "Charmeleon", tipo: "Fogo", nivel: 16, habilidade: "Lança-Chamas" },
  { nome: "Charizard", tipo: "Fogo/Voador", nivel: 36, habilidade: "Explosão de Fogo" },
  { nome: "Squirtle", tipo: "Água", nivel: 5, habilidade: "Jato d'Água" },
  { nome: "Wartortle", tipo: "Água", nivel: 16, habilidade: "Redemoinho" },
  { nome: "Blastoise", tipo: "Água", nivel: 36, habilidade: "Hidro Bomba" },
  { nome: "Caterpie", tipo: "Inseto", nivel: 3, habilidade: "Tiro de Seda" },
  { nome: "Weedle", tipo: "Inseto/Veneno", nivel: 3, habilidade: "Ferrão de Veneno" },
  { nome: "Kakuna", tipo: "Inseto/Veneno", nivel: 7, habilidade: "Pele Dura" },
  { nome: "Beedrill", tipo: "Inseto/Veneno", nivel: 10, habilidade: "Fúria de Abelha" },
  { nome: "Pidgey", tipo: "Normal/Voador", nivel: 3, habilidade: "Olhar Ágil" },
  { nome: "Pidgeotto", tipo: "Normal/Voador", nivel: 18, habilidade: "Ataque de Asas" },
  { nome: "Pidgeot", tipo: "Normal/Voador", nivel: 36, habilidade: "Vento Cortante" },
  { nome: "Rattata", tipo: "Normal", nivel: 2, habilidade: "Fuga" },
  { nome: "Raticate", tipo: "Normal", nivel: 20, habilidade: "Hiper Presa" },
  { nome: "Spearow", tipo: "Normal/Voador", nivel: 3, habilidade: "Bico de Aço" },
  { nome: "Fearow", tipo: "Normal/Voador", nivel: 20, habilidade: "Fúria" },
  { nome: "Ekans", tipo: "Veneno", nivel: 6, habilidade: "Olhar Sinistro" },
  { nome: "Arbok", tipo: "Veneno", nivel: 22, habilidade: "Escama Áspera" },
  { nome: "Pikachu", tipo: "Elétrico", nivel: 5, habilidade: "Estático" },
  { nome: "Raichu", tipo: "Elétrico", nivel: 30, habilidade: "Pára-raios" },
  { nome: "Sandshrew", tipo: "Terra", nivel: 5, habilidade: "Areia Veloze" },
  { nome: "Sandslash", tipo: "Terra", nivel: 22, habilidade: "Garras Afiadas" },
  { nome: "Nidoran♀", tipo: "Veneno", nivel: 3, habilidade: "Ponto Antiveneno" },
  { nome: "Nidorina", tipo: "Veneno", nivel: 16, habilidade: "Rivalidade" },
  { nome: "Nidoqueen", tipo: "Veneno/Terra", nivel: 32, habilidade: "Venenoso" },
  { nome: "Nidoran♂", tipo: "Veneno", nivel: 3, habilidade: "Rivalidade" },
  { nome: "Nidorino", tipo: "Veneno", nivel: 16, habilidade: "Fúria" },
  { nome: "Nidoking", tipo: "Veneno/Terra", nivel: 32, habilidade: "Presa Venenosa" },
  { nome: "Clefairy", tipo: "Fada", nivel: 5, habilidade: "Encanto Mágico" },
  { nome: "Clefable", tipo: "Fada", nivel: 25, habilidade: "Corpo Mágico" },
  { nome: "Vulpix", tipo: "Fogo", nivel: 5, habilidade: "Corpo de Chama" },
  { nome: "Ninetales", tipo: "Fogo", nivel: 25, habilidade: "Flash de Fogo" },
  { nome: "Jigglypuff", tipo: "Normal/Fada", nivel: 3, habilidade: "Encanto" },
  { nome: "Wigglytuff", tipo: "Normal/Fada", nivel: 24, habilidade: "Corpo Melhorado" },
  { nome: "Zubat", tipo: "Veneno/Voador", nivel: 3, habilidade: "Visão Noturna" },
  { nome: "Golbat", tipo: "Veneno/Voador", nivel: 22, habilidade: "Absorvente" },
  { nome: "Oddish", tipo: "Grama/Veneno", nivel: 5, habilidade: "Clorofila" },
  { nome: "Gloom", tipo: "Grama/Veneno", nivel: 21, habilidade: "Pó Estupefaciente" },
  { nome: "Vileplume", tipo: "Grama/Veneno", nivel: 32, habilidade: "Efeito Espalhado" },
  { nome: "Paras", tipo: "Inseto/Grama", nivel: 3, habilidade: "Efeito Espalhado" },
  { nome: "Parasect", tipo: "Inseto/Grama", nivel: 24, habilidade: "Corpo Seco" },
  { nome: "Venonat", tipo: "Inseto/Veneno", nivel: 5, habilidade: "Olhos Compostos" },
  { nome: "Venomoth", tipo: "Inseto/Veneno", nivel: 31, habilidade: "Escama Mágica" },
  { nome: "Diglett", tipo: "Terra", nivel: 5, habilidade: "Areia Veloze" },
  { nome: "Dugtrio", tipo: "Terra", nivel: 26, habilidade: "Fuga" },
  { nome: "Meowth", tipo: "Normal", nivel: 5, habilidade: "Colecionar" },
  { nome: "Persian", tipo: "Normal", nivel: 28, habilidade: "Olhos Penetrantes" },
  { nome: "Psyduck", tipo: "Água", nivel: 5, habilidade: "Molhado" },
  { nome: "Golduck", tipo: "Água", nivel: 28, habilidade: "Nado Rápido" },
  { nome: "Mankey", tipo: "Lutador", nivel: 3, habilidade: "Ímpeto" },
  { nome: "Primeape", tipo: "Lutador", nivel: 28, habilidade: "Fúria" },
  { nome: "Growlithe", tipo: "Fogo", nivel: 5, habilidade: "Intimidação" },
  { nome: "Arcanine", tipo: "Fogo", nivel: 34, habilidade: "Flash de Fogo" },
  { nome: "Poliwag", tipo: "Água", nivel: 5, habilidade: "Absorção de Água" },
  { nome: "Poliwhirl", tipo: "Água", nivel: 25, habilidade: "Umidade" },
  { nome: "Poliwrath", tipo: "Água/Lutador", nivel: 40, habilidade: "Absorvente" },
  { nome: "Abra", tipo: "Psíquico", nivel: 5, habilidade: "Sincronia" },
  { nome: "Kadabra", tipo: "Psíquico", nivel: 16, habilidade: "Sincronia" },
  { nome: "Alakazam", tipo: "Psíquico", nivel: 36, habilidade: "Corpo Mágico" },
  { nome: "Machop", tipo: "Lutador", nivel: 5, habilidade: "Garras Vasto" },
  { nome: "Machoke", tipo: "Lutador", nivel: 28, habilidade: "Força Bruta" },
  { nome: "Machamp", tipo: "Lutador", nivel: 45, habilidade: "Sem Limite" },
  { nome: "Bellsprout", tipo: "Grama/Veneno", nivel: 5, habilidade: "Clorofila" },
  { nome: "Weepinbell", tipo: "Grama/Veneno", nivel: 21, habilidade: "Gota Venenosa" },
  { nome: "Victreebel", tipo: "Grama/Veneno", nivel: 32, habilidade: "Engole Tudo" },
  { nome: "Tentacool", tipo: "Água/Veneno", nivel: 5, habilidade: "Corpo Limpador" },
  { nome: "Tentacruel", tipo: "Água/Veneno", nivel: 30, habilidade: "Corpo Limpador" },
  { nome: "Geodude", tipo: "Pedra/Terra", nivel: 5, habilidade: "Cabeça de Pedra" },
  { nome: "Graveler", tipo: "Pedra/Terra", nivel: 25, habilidade: "Cabeça de Rocha" },
  { nome: "Golem", tipo: "Pedra/Terra", nivel: 40, habilidade: "Frágil" },
  { nome: "Ponyta", tipo: "Fogo", nivel: 5, habilidade: "Fuga" },
  { nome: "Rapidash", tipo: "Fogo", nivel: 40, habilidade: "Chama Ígnea" },
  { nome: "Slowpoke", tipo: "Água/Psíquico", nivel: 5, habilidade: "Oblíquo" },
  { nome: "Slowbro", tipo: "Água/Psíquico", nivel: 37, habilidade: "Dono" },
  { nome: "Magnemite", tipo: "Elétrico/Aço", nivel: 15, habilidade: "Magnetismo" },
  { nome: "Magneton", tipo: "Elétrico/Aço", nivel: 30, habilidade: "Aço Forte" },
  { nome: "Farfetch'd", tipo: "Normal/Voador", nivel: 20, habilidade: "Esperto" },
  { nome: "Doduo", tipo: "Normal/Voador", nivel: 10, habilidade: "Fuga" },
  { nome: "Dodrio", tipo: "Normal/Voador", nivel: 35, habilidade: "Fuga" },
  { nome: "Seel", tipo: "Água", nivel: 10, habilidade: "Groselha" },
  { nome: "Dewgong", tipo: "Água/Gelo", nivel: 34, habilidade: "Corpo Gordo" },
  { nome: "Grimer", tipo: "Veneno", nivel: 10, habilidade: "Cheiro Repugnante" },
  { nome: "Muk", tipo: "Veneno", nivel: 38, habilidade: "Cheiro Repugnante" },
  { nome: "Shellder", tipo: "Água", nivel: 5, habilidade: "Concha Dura" },
  { nome: "Cloyster", tipo: "Água/Gelo", nivel: 30, habilidade: "Habilidade Externa" },
  { nome: "Gastly", tipo: "Fantasma/Veneno", nivel: 10, habilidade: "Levitação" },
  { nome: "Haunter", tipo: "Fantasma/Veneno", nivel: 25, habilidade: "Levitação" },
  { nome: "Gengar", tipo: "Fantasma/Veneno", nivel: 45, habilidade: "Cursed Body" },
  { nome: "Onix", tipo: "Pedra/Terra", nivel: 15, habilidade: "Cabeça de Rocha" },
  { nome: "Drowzee", tipo: "Psíquico", nivel: 10, habilidade: "Insônia" },
  { nome: "Hypno", tipo: "Psíquico", nivel: 37, habilidade: "Premonição" },
  { nome: "Krabby", tipo: "Água", nivel: 5, habilidade: "Hiper Presa" },
  { nome: "Kingler", tipo: "Água", nivel: 28, habilidade: "Garras Afiadas" },
  { nome: "Voltorb", tipo: "Elétrico", nivel: 10, habilidade: "Som" },
  { nome: "Electrode", tipo: "Elétrico", nivel: 30, habilidade: "Som" },
  { nome: "Exeggcute", tipo: "Grama/Psíquico", nivel: 10, habilidade: "Colheita" },
  { nome: "Exeggutor", tipo: "Grama/Psíquico", nivel: 35, habilidade: "Colheita" },
  { nome: "Cubone", tipo: "Terra", nivel: 10, habilidade: "Cabeça de Rocha" },
  { nome: "Marowak", tipo: "Terra", nivel: 28, habilidade: "Casco de Fogo" },
  { nome: "Hitmonlee", tipo: "Lutador", nivel: 30, habilidade: "Chute Flexível" },
  { nome: "Hitmonchan", tipo: "Lutador", nivel: 30, habilidade: "Soco de Ferro" },
  { nome: "Lickitung", tipo: "Normal", nivel: 15, habilidade: "Próprio" },
  { nome: "Koffing", tipo: "Veneno", nivel: 15, habilidade: "Levitação" },
  { nome: "Weezing", tipo: "Veneno", nivel: 35, habilidade: "Levitação" },
  { nome: "Rhyhorn", tipo: "Pedra/Terra", nivel: 15, habilidade: "Cabeça de Rocha" },
  { nome: "Rhydon", tipo: "Pedra/Terra", nivel: 42, habilidade: "Aço Forte" },
  { nome: "Chansey", tipo: "Normal", nivel: 12, habilidade: "Cura Natural" },
  { nome: "Tangela", tipo: "Grama", nivel: 15, habilidade: "Folha de Guarda" },
  { nome: "Kangaskhan", tipo: "Normal", nivel: 20, habilidade: "Cedo" },
  { nome: "Horsea", tipo: "Água", nivel: 5, habilidade: "Nado Rápido" },
  { nome: "Seadra", tipo: "Água", nivel: 32, habilidade: "Veneno de Ponta" },
  { nome: "Goldeen", tipo: "Água", nivel: 10, habilidade: "Nado Rápido" },
  { nome: "Seaking", tipo: "Água", nivel: 33, habilidade: "Groselha" },
  { nome: "Staryu", tipo: "Água", nivel: 10, habilidade: "Regeneração" },
  { nome: "Starmie", tipo: "Água/Psíquico", nivel: 30, habilidade: "Análise" },
  { nome: "Mr. Mime", tipo: "Psíquico/Fada", nivel: 20, habilidade: "Filtro Sonoro" },
  { nome: "Scyther", tipo: "Inseto/Voador", nivel: 20, habilidade: "Técnico" },
  { nome: "Jynx", tipo: "Gelo/Psíquico", nivel: 30, habilidade: "Corpo Gordo" },
  { nome: "Electabuzz", tipo: "Elétrico", nivel: 30, habilidade: "Estático" },
  { nome: "Magmar", tipo: "Fogo", nivel: 30, habilidade: "Corpo de Chama" },
  { nome: "Pinsir", tipo: "Inseto", nivel: 25, habilidade: "Hiper Presa" },
  { nome: "Tauros", tipo: "Normal", nivel: 20, habilidade: "Intimidação" },
  { nome: "Magikarp", tipo: "Água", nivel: 1, habilidade: "Nado Rápido" },
  { nome: "Gyarados", tipo: "Água/Voador", nivel: 20, habilidade: "Intimidação" },
  { nome: "Lapras", tipo: "Água/Gelo", nivel: 30, habilidade: "Casca de Água" },
  { nome: "Ditto", tipo: "Normal", nivel: 20, habilidade: "Transformação" },
  { nome: "Eevee", tipo: "Normal", nivel: 10, habilidade: "Adaptação" },
  { nome: "Vaporeon", tipo: "Água", nivel: 25, habilidade: "Absorção de Água" },
  { nome: "Jolteon", tipo: "Elétrico", nivel: 25, habilidade: "Absorvente" },
  { nome: "Flareon", tipo: "Fogo", nivel: 25, habilidade: "Flash de Fogo" },
  { nome: "Porygon", tipo: "Normal", nivel: 15, habilidade: "Traço" },
  { nome: "Omanyte", tipo: "Pedra/Água", nivel: 20, habilidade: "Frágil" },
  { nome: "Omastar", tipo: "Pedra/Água", nivel: 40, habilidade: "Concha Dura" },
  { nome: "Kabuto", tipo: "Pedra/Água", nivel: 20, habilidade: "Frágil" },
  { nome: "Kabutops", tipo: "Pedra/Água", nivel: 40, habilidade: "Nado Rápido" },
  { nome: "Aerodactyl", tipo: "Pedra/Voador", nivel: 35, habilidade: "Cabeça de Rocha" },
  { nome: "Snorlax", tipo: "Normal", nivel: 30, habilidade: "Imunidade" },
  { nome: "Articuno", tipo: "Gelo/Voador", nivel: 50, habilidade: "Corpo de Pressão" },
  { nome: "Zapdos", tipo: "Elétrico/Voador", nivel: 50, habilidade: "Estático" },
  { nome: "Moltres", tipo: "Fogo/Voador", nivel: 50, habilidade: "Corpo de Chama" },
  { nome: "Dratini", tipo: "Dragão", nivel: 5, habilidade: "Muda de Pele" },
  { nome: "Dragonair", tipo: "Dragão", nivel: 30, habilidade: "Corpo Interno" },
  { nome: "Dragonite", tipo: "Dragão/Voador", nivel: 55, habilidade: "Corpo Interno" },
  { nome: "Mewtwo", tipo: "Psíquico", nivel: 70, habilidade: "Pressão" },
  { nome: "Mew", tipo: "Psíquico", nivel: 10, habilidade: "Sincronia" },
  { nome: "Chikorita", tipo: "Grama", nivel: 16, habilidade: "Crescimento excessivo" }
])